//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by mp3infp_setup.rc
//
#define ID_MENU_COPY                    100
#define ID_MENU_PASTE                   101
#define IDB_FFW                         102
#define IDB_PAUSE                       103
#define IDB_PLAY                        104
#define IDB_REW                         105
#define IDB_STOP                        106
#define IDC_BUTTON_ADD_VALUE            107
#define IDC_BUTTON_DEL_TAG              108
#define IDC_BUTTON_DEL_VALUE            109
#define IDC_BUTTON_FFW                  110
#define IDC_BUTTON_MAKE_TAG             111
#define IDC_BUTTON_PAUSE                112
#define IDC_BUTTON_PLAY                 113
#define IDC_BUTTON_REW                  114
#define IDC_BUTTON_STOP                 115
#define IDC_CHECK_ADD_CONTEXTMENU       116
#define IDC_CHECK_AOT                   117
#define IDC_CHECK_COLUMN_8_3            118
#define IDC_CHECK_DISABLE_CDROM         119
#define IDC_CHECK_DISABLE_FDD           120
#define IDC_CHECK_DISABLE_NETWORK       121
#define IDC_CHECK_DISABLE_REMOVABLE     122
#define IDC_CHECK_ID3V1SCMPX_GENRE      123
#define IDC_CHECK_INFOTIP_ENABLE        124
#define IDC_CHECK_PROP_ENABLE           125
#define IDC_CHECK_RIFF_DISABLE          126
#define IDC_CHECK_SELECT_DRIVE          127
#define IDC_CHECK_UNSYNC                128
#define IDC_COLUMN_ENABLE               129
#define IDC_COMBO_LANGUAGE              130
#define IDC_COMPILATION                 131
#define IDC_COPY_FROM_ID3V1             132
#define IDC_COPY_FROM_ID3V2             133
#define IDC_COPY_FROM_RIFF              134
#define IDC_DEFAULT                     135
#define IDC_EDIT_ART                    136
#define IDC_EDIT_BPM                    137
#define IDC_EDIT_CMT                    138
#define IDC_EDIT_COMP                   139
#define IDC_EDIT_COMPOSE                140
#define IDC_EDIT_COP                    141
#define IDC_EDIT_COPYRIGHT              142
#define IDC_EDIT_CRD                    143
#define IDC_EDIT_DISC                   144
#define IDC_EDIT_DISC2                  145
#define IDC_EDIT_ENC                    146
#define IDC_EDIT_ENC2                   147
#define IDC_EDIT_ENG                    148
#define IDC_EDIT_FILE                   149
#define IDC_EDIT_FILENAME               150
#define IDC_EDIT_FORMAT                 151
#define IDC_EDIT_GNR                    152
#define IDC_EDIT_GRP                    153
#define IDC_EDIT_ID3VER                 154
#define IDC_EDIT_INFOTIP_FORMAT         155
#define IDC_EDIT_INFOTIP_INFO           156
#define IDC_EDIT_LAME                   157
#define IDC_EDIT_LIST                   158
#define IDC_EDIT_NAM                    159
#define IDC_EDIT_NAME                   160
#define IDC_EDIT_ORGART                 161
#define IDC_EDIT_PRD                    162
#define IDC_EDIT_RIFF_SOFT              163
#define IDC_EDIT_SBJ                    164
#define IDC_EDIT_SFT                    165
#define IDC_EDIT_SRC                    166
#define IDC_EDIT_TOOL                   167
#define IDC_EDIT_TRACK                  168
#define IDC_EDIT_TRK                    169
#define IDC_EDIT_TRK2                   170
#define IDC_EDIT_UNICODE                171
#define IDC_EDIT_URL                    172
#define IDC_EDIT_URL1                   173
#define IDC_EDIT_URL2                   174
#define IDC_EDIT_VALUE                  175
#define IDC_HELPVIEW                    176
#define IDC_ICON1                       177
#define IDC_LIST_VALUE                  178
#define IDC_PROGRESS1                   179
#define IDC_RADIO_AVICODEC_FIND1        180
#define IDC_RADIO_AVICODEC_FIND2        181
#define IDC_RADIO_AVICODEC_FIND3        182
#define IDC_RADIO_AVICODEC_FIND4        183
#define IDC_RADIO_PATH1                 184
#define IDC_RADIO_PATH2                 185
#define IDC_RADIO_PATH3                 186
#define IDC_SAVE_TIMESTAMP              187
#define IDC_SETUP                       188
#define IDC_STATIC_ART                  189
#define IDC_STATIC_AUDIO_INFO           190
#define IDC_STATIC_AVI_VER              191
#define IDC_STATIC_AVI_VER_             192
#define IDC_STATIC_BPM                  193
#define IDC_STATIC_BROADCAST            194
#define IDC_STATIC_CMT                  195
#define IDC_STATIC_CMT2                 196
#define IDC_STATIC_CMT3                 197
#define IDC_STATIC_CMT4                 198
#define IDC_STATIC_CMT5                 199
#define IDC_STATIC_COMP                 200
#define IDC_STATIC_COMPOSE              201
#define IDC_STATIC_COP                  202
#define IDC_STATIC_COPYRIGHT            203
#define IDC_STATIC_CRD                  204
#define IDC_STATIC_DISC                 205
#define IDC_STATIC_ENC                  206
#define IDC_STATIC_ENC2                 207
#define IDC_STATIC_ENCODE               208
#define IDC_STATIC_ENG                  209
#define IDC_STATIC_ETC_INFO             210
#define IDC_STATIC_FILE                 211
#define IDC_STATIC_FORMAT               212
#define IDC_STATIC_FORMAT_              213
#define IDC_STATIC_FORMAT_A             214
#define IDC_STATIC_FORMAT_A_            215
#define IDC_STATIC_FORMAT_INFO          216
#define IDC_STATIC_FORMAT_V             217
#define IDC_STATIC_FORMAT_V_            218
#define IDC_STATIC_GNR                  219
#define IDC_STATIC_GRP                  220
#define IDC_STATIC_ID3GUIDE             221
#define IDC_STATIC_ID3TAGV1_NOTE        222
#define IDC_STATIC_ID3VER               223
#define IDC_STATIC_INFO                 224
#define IDC_STATIC_INFOTIP_FORMAT       225
#define IDC_STATIC_IS_PROTECTED         226
#define IDC_STATIC_NAM                  227
#define IDC_STATIC_NOT_MP3              228
#define IDC_STATIC_ORGART               229
#define IDC_STATIC_PRD                  230
#define IDC_STATIC_SEEKABLE             231
#define IDC_STATIC_SFT                  232
#define IDC_STATIC_SIZE_INFO            233
#define IDC_STATIC_SOFT_DEFAULT         234
#define IDC_STATIC_SRC                  235
#define IDC_STATIC_TIME                 236
#define IDC_STATIC_TIME_                237
#define IDC_STATIC_TOOL                 238
#define IDC_STATIC_TRACK                239
#define IDC_STATIC_TRANSLATE            240
#define IDC_STATIC_TRANSLATOR           241
#define IDC_STATIC_TRK                  242
#define IDC_STATIC_URL                  243
#define IDC_STATIC_URL1                 244
#define IDC_STATIC_URL2                 245
#define IDC_STATIC_VER_INFO             246
#define IDC_STATIC_WINAMP               247
#define IDC_URL_JUMP                    248
#define IDD_DIALOG_OGG_EXTTAG           249
#define IDD_PAGE_APE                    250
#define IDD_PAGE_AVI                    251
#define IDD_PAGE_M3U                    252
#define IDD_PAGE_MP3_APE                253
#define IDD_PAGE_MP3_ID3V1              254
#define IDD_PAGE_MP3_ID3V2              255
#define IDD_PAGE_MP3_LAME               256
#define IDD_PAGE_MP3_RMP                257
#define IDD_PAGE_MP4                    258
#define IDD_PAGE_OGG                    259
#define IDD_PAGE_VQF                    260
#define IDD_PAGE_WAVE                   261
#define IDD_PAGE_WMA                    262
#define IDD_SETUP                       263
#define IDD_SETUP_APE                   264
#define IDD_SETUP_AVI                   265
#define IDD_SETUP_M3U                   266
#define IDD_SETUP_MP3                   267
#define IDD_SETUP_OGG                   268
#define IDD_SETUP_VQF                   269
#define IDD_SETUP_WAVE                  270
#define IDD_SETUP_WMA                   271
#define IDD_WRITE_PROGRESS              272
#define IDI_ICON1                       273
#define IDD_SETUP_MP4                   273
#define IDR_MENU_PROPERTY_CONTEXT       274
#define IDS_AVI_UNCODE                  275
#define IDS_CAN_NOT_CREATE_TEMP_FILE    276
#define IDS_CAN_NOT_HTMLHELP_OPEN       277
#define IDS_COMCTL32_INFO               278
#define IDS_CPL_CAPTION                 279
#define IDS_CPL_INFO                    280
#define IDS_CPL_NAME                    281
#define IDS_INFOTIP_MAXLINE_OVER        282
#define IDS_INFOTIP_NOTINFO             283
#define IDS_LANG_VER_ERROR              285
#define IDS_LANGUAGE_NAME               286
#define IDS_LANGUAGE_VER                287
#define IDS_MEMERROR                    288
#define IDS_NO_AUDIO_STREAM             289
#define IDS_NO_VIDEO_STREAM             290
#define IDS_OGG_BAD_CHAR                291
#define IDS_OVER_2G                     292
#define IDS_PAGE_BROKEN                 293
#define IDS_PAGE_CAN_NOT_OPEN           294
#define IDS_PAGE_MP3APE_DEL_APE         295
#define IDS_PAGE_MP3APE_MAKE_APE        296
#define IDS_PAGE_MP3ID3V1_CAN_NOT_DEL   297
#define IDS_PAGE_MP3ID3V1_COUNT         298
#define IDS_PAGE_MP3ID3V1_COUNT_OVER    299
#define IDS_PAGE_MP3ID3V1_DEL_ID3TAG    300
#define IDS_PAGE_MP3ID3V1_MAKE_ID3TAG   301
#define IDS_PAGE_MP3ID3V1_NOTFOUND_ID3  302
#define IDS_PAGE_MP3ID3V11_COUNT        303
#define IDS_PAGE_MP3ID3V11_COUNT_OVER   304
#define IDS_PAGE_MP3ID3V2_CAN_NOT_MAKE  305
#define IDS_PAGE_MP3ID3V2_CAN_NOT_MAKE_APE 306
#define IDS_PAGE_MP3ID3V2_CAN_NOT_MAKE2 307
#define IDS_PAGE_MP3ID3V2_CANNOT_WRITE  308
#define IDS_PAGE_MP3ID3V2_DEL_ID3TAG    309
#define IDS_PAGE_MP3ID3V2_MAKE_ID3TAG   310
#define IDS_PAGE_MP3RIFF_BROKEN_RIFF    311
#define IDS_PAGE_MP3RIFF_CAN_NOT_MAKE   312
#define IDS_PAGE_MP3RIFF_CAN_NOT_MAKE_APE 313
#define IDS_PAGE_MP3RIFF_CAN_NOT_MAKE2  314
#define IDS_PAGE_MP3RIFF_CONV_MP3       315
#define IDS_PAGE_MP3RIFF_CONV_RMP       316
#define IDS_PAGE_THIS_READONLY          317
#define IDS_PAGE_VQF_BROKEN             318
#define IDS_PLEASE_TAG_NAME             319
#define IDS_RELOAD_CPL                  320
#define IDS_TRANSLATOR                  321
#define IDS_UNKNOWN                     322
#define IDS_VIEW_PROP                   323
#define IDC_EDIT_AART                   324
#define IDC_STATIC_AART                 325
#define IDS_COLUMN_8_3                  1000
#define IDS_COLUMN_ALBUM                1001
#define IDS_COLUMN_ARTIST               1002
#define IDS_COLUMN_AUDIO_FORMAT         1003
#define IDS_COLUMN_AVIVER               1004
#define IDS_COLUMN_COMMENT              1005
#define IDS_COLUMN_DATE                 1006
#define IDS_COLUMN_DESC_8_3             1007
#define IDS_COLUMN_DESC_ALBUM           1008
#define IDS_COLUMN_DESC_ARTIST          1009
#define IDS_COLUMN_DESC_AUDIO_FORMAT    1010
#define IDS_COLUMN_DESC_AVIVER          1011
#define IDS_COLUMN_DESC_COMMENT         1012
#define IDS_COLUMN_DESC_DATE            1013
#define IDS_COLUMN_DESC_EXTENSION       1014
#define IDS_COLUMN_DESC_GENRE           1015
#define IDS_COLUMN_DESC_SIZE            1016
#define IDS_COLUMN_DESC_TAGTYPE         1017
#define IDS_COLUMN_DESC_TIME            1018
#define IDS_COLUMN_DESC_TITLE           1019
#define IDS_COLUMN_DESC_TRACK           1020
#define IDS_COLUMN_DESC_VIDEO_FORMAT    1021
#define IDS_COLUMN_EXTENSION            1022
#define IDS_COLUMN_GENRE                1023
#define IDS_COLUMN_SIZE                 1024
#define IDS_COLUMN_TAGTYPE              1025
#define IDS_COLUMN_TIME                 1026
#define IDS_COLUMN_TITLE                1027
#define IDS_COLUMN_TRACK                1028
#define IDS_COLUMN_VIDEO_FORMAT         1029
#define IDS_DEF_INFOTIP_INF_APE_FORMAT  1202
#define IDS_DEF_INFOTIP_INF_AVI_FORMAT  1203
#define IDS_DEF_INFOTIP_INF_MP3_FORMAT  1204
#define IDS_DEF_INFOTIP_INF_OGG_FORMAT  1205
#define IDS_DEF_INFOTIP_INF_VQF_FORMAT  1206
#define IDS_DEF_INFOTIP_INF_WAVE_FORMAT 1207
#define IDS_DEF_INFOTIP_INF_WMA_FORMAT  1208
#define IDS_DEF_INFOTIP_INF_MP4_FORMAT  1209
#define IDS_DEF_INFOTIP_MP3_FORMAT      1300
#define IDS_DEF_INFOTIP_OGG_FORMAT      1301
#define IDS_DEF_INFOTIP_VQF_FORMAT      1302
#define IDS_DEF_INFOTIP_WAVE_FORMAT     1303
#define IDS_DEF_INFOTIP_WMA_FORMAT      1304
#define IDS_DEF_INFOTIP_APE_FORMAT      1305
#define IDS_DEF_INFOTIP_AVI_FORMAT      1306
#define IDS_DEF_INFOTIP_MP4_FORMAT      1307

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        6002
#define _APS_NEXT_COMMAND_VALUE         7000
#define _APS_NEXT_CONTROL_VALUE         8000
#define _APS_NEXT_SYMED_VALUE           9000
#endif
#endif
