//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by mp3infp.rc
//
#define IDD_DIALOG_OGG_EXTTAG           100
#define IDD_PAGE_APE                    101
#define IDD_PAGE_AVI                    102
#define IDD_PAGE_M3U                    103
#define IDD_PAGE_MP3_APE                104
#define IDD_PAGE_MP3_ID3V1              105
#define IDD_PAGE_MP3_ID3V2              106
#define IDD_PAGE_MP3_LAME               107
#define IDD_PAGE_MP3_RMP                108
#define IDD_PAGE_MP4                    109
#define IDD_PAGE_OGG                    110
#define IDD_PAGE_VQF                    111
#define IDD_PAGE_WAVE                   112
#define IDD_PAGE_WMA                    113
#define IDD_SETUP                       114
#define IDD_SETUP_APE                   115
#define IDD_SETUP_AVI                   116
#define IDD_SETUP_M3U                   117
#define IDD_SETUP_MP3                   118
#define IDD_SETUP_MP4                   119
#define IDD_SETUP_OGG                   120
#define IDD_SETUP_VQF                   121
#define IDD_SETUP_WAVE                  122
#define IDD_SETUP_WMA                   123
#define IDD_WRITE_PROGRESS              124
#define IDR_MENU_PROPERTY_CONTEXT       125
#define IDS_AVI_UNCODE                  126
#define IDS_COLUMN_8_3                  129
#define IDS_COLUMN_ALBUM                130
#define IDS_COLUMN_ARTIST               131
#define IDS_COLUMN_AUDIO_FORMAT         132
#define IDS_COLUMN_AVIVER               133
#define IDS_COLUMN_COMMENT              134
#define IDS_COLUMN_DATE                 135
#define IDS_COLUMN_DESC_8_3             136
#define IDS_COLUMN_DESC_ALBUM           137
#define IDS_COLUMN_DESC_ARTIST          138
#define IDS_COLUMN_DESC_AUDIO_FORMAT    139
#define IDS_COLUMN_DESC_AVIVER          140
#define IDS_COLUMN_DESC_COMMENT         141
#define IDS_COLUMN_DESC_DATE            142
#define IDS_COLUMN_DESC_EXTENSION       143
#define IDS_COLUMN_DESC_GENRE           144
#define IDS_COLUMN_DESC_SIZE            145
#define IDS_COLUMN_DESC_TAGTYPE         146
#define IDS_COLUMN_DESC_TIME            147
#define IDS_COLUMN_DESC_TITLE           148
#define IDS_COLUMN_DESC_TRACK           149
#define IDS_COLUMN_DESC_VIDEO_FORMAT    150
#define IDS_COLUMN_EXTENSION            151
#define IDS_COLUMN_GENRE                152
#define IDS_COLUMN_SIZE                 153
#define IDS_COLUMN_TAGTYPE              154
#define IDS_COLUMN_TIME                 155
#define IDS_COLUMN_TITLE                156
#define IDS_COLUMN_TRACK                157
#define IDS_COLUMN_VIDEO_FORMAT         158
#define IDS_CPL_CAPTION                 160
#define IDS_CPL_NAME                    162
#define IDS_DEF_INFOTIP_APE_FORMAT      163
#define IDS_DEF_INFOTIP_AVI_FORMAT      164
#define IDS_DEF_INFOTIP_INF_APE_FORMAT  165
#define IDS_DEF_INFOTIP_INF_AVI_FORMAT  166
#define IDS_DEF_INFOTIP_INF_MP3_FORMAT  167
#define IDS_DEF_INFOTIP_INF_MP4_FORMAT  168
#define IDS_DEF_INFOTIP_INF_OGG_FORMAT  169
#define IDS_DEF_INFOTIP_INF_VQF_FORMAT  170
#define IDS_DEF_INFOTIP_INF_WAVE_FORMAT 171
#define IDS_DEF_INFOTIP_INF_WMA_FORMAT  172
#define IDS_DEF_INFOTIP_MP3_FORMAT      173
#define IDS_DEF_INFOTIP_MP4_FORMAT      174
#define IDS_DEF_INFOTIP_OGG_FORMAT      175
#define IDS_DEF_INFOTIP_VQF_FORMAT      176
#define IDS_DEF_INFOTIP_WAVE_FORMAT     177
#define IDS_DEF_INFOTIP_WMA_FORMAT      178
#define IDS_INFOTIP_MAXLINE_OVER        179
#define IDS_INFOTIP_NOTINFO             180
#define IDS_LANGUAGE_NAME               181
#define IDS_LANGUAGE_VER                182
#define IDS_LANG_VER_ERROR              183
#define IDS_MEMERROR                    184
#define IDS_NO_AUDIO_STREAM             185
#define IDS_NO_VIDEO_STREAM             186
#define IDS_OGG_BAD_CHAR                187
#define IDS_OVER_2G                     188
#define IDS_PAGE_BROKEN                 189
#define IDS_PAGE_CAN_NOT_OPEN           190
#define IDS_PAGE_MP3APE_DEL_APE         191
#define IDS_PAGE_MP3APE_MAKE_APE        192
#define IDS_PAGE_MP3ID3V11_COUNT        193
#define IDS_PAGE_MP3ID3V11_COUNT_OVER   194
#define IDS_PAGE_MP3ID3V1_CAN_NOT_DEL   195
#define IDS_PAGE_MP3ID3V1_COUNT         196
#define IDS_PAGE_MP3ID3V1_COUNT_OVER    197
#define IDS_PAGE_MP3ID3V1_DEL_ID3TAG    198
#define IDS_PAGE_MP3ID3V1_MAKE_ID3TAG   199
#define IDS_PAGE_MP3ID3V1_NOTFOUND_ID3  200
#define IDS_PAGE_MP3ID3V2_CANNOT_WRITE  201
#define IDS_PAGE_MP3ID3V2_CAN_NOT_MAKE  202
#define IDS_PAGE_MP3ID3V2_CAN_NOT_MAKE2 203
#define IDS_PAGE_MP3ID3V2_CAN_NOT_MAKE_APE 204
#define IDS_PAGE_MP3ID3V2_DEL_ID3TAG    205
#define IDS_PAGE_MP3ID3V2_MAKE_ID3TAG   206
#define IDS_PAGE_MP3RIFF_CAN_NOT_MAKE   208
#define IDS_PAGE_MP3RIFF_CAN_NOT_MAKE2  209
#define IDS_PAGE_MP3RIFF_CAN_NOT_MAKE_APE 210
#define IDS_PAGE_MP3RIFF_CONV_MP3       211
#define IDS_PAGE_MP3RIFF_CONV_RMP       212
#define IDS_PAGE_THIS_READONLY          213
#define IDS_PLEASE_TAG_NAME             215
#define IDS_RELOAD_CPL                  216
#define IDS_TRANSLATOR                  217
#define IDS_UNKNOWN                     218
#define IDS_VIEW_PROP                   219
#define IDB_FFW                         1000
#define IDB_PAUSE                       1001
#define IDB_PLAY                        1002
#define IDB_REW                         1003
#define IDB_STOP                        1004
#define IDC_BUTTON_ADD_VALUE            1005
#define IDC_BUTTON_DEL_TAG              1006
#define IDC_BUTTON_DEL_VALUE            1007
#define IDC_BUTTON_FFW                  1008
#define IDC_BUTTON_MAKE_TAG             1009
#define IDC_BUTTON_PAUSE                1010
#define IDC_BUTTON_PLAY                 1011
#define IDC_BUTTON_REW                  1012
#define IDC_BUTTON_STOP                 1013
#define IDC_CHECK_ADD_CONTEXTMENU       1014
#define IDC_CHECK_AOT                   1015
#define IDC_CHECK_COLUMN_8_3            1016
#define IDC_CHECK_DISABLE_CDROM         1017
#define IDC_CHECK_DISABLE_FDD           1018
#define IDC_CHECK_DISABLE_NETWORK       1019
#define IDC_CHECK_DISABLE_REMOVABLE     1020
#define IDC_CHECK_ID3V1SCMPX_GENRE      1021
#define IDC_CHECK_INFOTIP_ENABLE        1022
#define IDC_CHECK_PROP_ENABLE           1023
#define IDC_CHECK_RIFF_DISABLE          1024
#define IDC_CHECK_SELECT_DRIVE          1025
#define IDC_CHECK_UNSYNC                1026
#define IDC_COLUMN_ENABLE               1027
#define IDC_COMBO_LANGUAGE              1028
#define IDC_COMPILATION                 1029
#define IDC_COPY_FROM_ID3V1             1030
#define IDC_COPY_FROM_ID3V2             1031
#define IDC_COPY_FROM_RIFF              1032
#define IDC_DEFAULT                     1033
#define IDC_EDIT_AART                   1034
#define IDC_EDIT_ART                    1035
#define IDC_EDIT_BPM                    1036
#define IDC_EDIT_CMT                    1037
#define IDC_EDIT_COMP                   1038
#define IDC_EDIT_COMPOSE                1039
#define IDC_EDIT_COP                    1040
#define IDC_EDIT_COPYRIGHT              1041
#define IDC_EDIT_CRD                    1042
#define IDC_EDIT_DISC                   1043
#define IDC_EDIT_DISC2                  1044
#define IDC_EDIT_ENC                    1045
#define IDC_EDIT_ENC2                   1046
#define IDC_EDIT_ENG                    1047
#define IDC_EDIT_FILE                   1048
#define IDC_EDIT_FILENAME               1049
#define IDC_EDIT_FORMAT                 1050
#define IDC_EDIT_GNR                    1051
#define IDC_EDIT_GRP                    1052
#define IDC_EDIT_ID3VER                 1053
#define IDC_EDIT_INFOTIP_FORMAT         1054
#define IDC_EDIT_INFOTIP_INFO           1055
#define IDC_EDIT_LAME                   1056
#define IDC_EDIT_LIST                   1057
#define IDC_EDIT_NAM                    1058
#define IDC_EDIT_NAME                   1059
#define IDC_EDIT_ORGART                 1060
#define IDC_EDIT_PRD                    1061
#define IDC_EDIT_RIFF_SOFT              1062
#define IDC_EDIT_SBJ                    1063
#define IDC_EDIT_SFT                    1064
#define IDC_EDIT_SRC                    1065
#define IDC_EDIT_TOOL                   1066
#define IDC_EDIT_TRACK                  1067
#define IDC_EDIT_TRK                    1068
#define IDC_EDIT_TRK2                   1069
#define IDC_EDIT_UNICODE                1070
#define IDC_EDIT_URL                    1071
#define IDC_EDIT_URL1                   1072
#define IDC_EDIT_URL2                   1073
#define IDC_EDIT_VALUE                  1074
#define IDC_HELPVIEW                    1075
#define IDC_ICON1                       1076
#define IDC_LIST_VALUE                  1077
#define IDC_PROGRESS1                   1078
#define IDC_RADIO_AVICODEC_FIND1        1079
#define IDC_RADIO_AVICODEC_FIND2        1080
#define IDC_RADIO_AVICODEC_FIND3        1081
#define IDC_RADIO_AVICODEC_FIND4        1082
#define IDC_RADIO_PATH1                 1083
#define IDC_RADIO_PATH2                 1084
#define IDC_RADIO_PATH3                 1085
#define IDC_SAVE_TIMESTAMP              1086
#define IDC_SETUP                       1087
#define IDC_STATIC_AART                 1088
#define IDC_STATIC_ART                  1089
#define IDC_STATIC_AUDIO_INFO           1090
#define IDC_STATIC_AVI_VER              1091
#define IDC_STATIC_AVI_VER_             1092
#define IDC_STATIC_BPM                  1093
#define IDC_STATIC_BROADCAST            1094
#define IDC_STATIC_CMT                  1095
#define IDC_STATIC_CMT2                 1096
#define IDC_STATIC_CMT3                 1097
#define IDC_STATIC_CMT4                 1098
#define IDC_STATIC_CMT5                 1099
#define IDC_STATIC_COMP                 1100
#define IDC_STATIC_COMPOSE              1101
#define IDC_STATIC_COP                  1102
#define IDC_STATIC_COPYRIGHT            1103
#define IDC_STATIC_CRD                  1104
#define IDC_STATIC_DISC                 1105
#define IDC_STATIC_ENC                  1106
#define IDC_STATIC_ENC2                 1107
#define IDC_STATIC_ENCODE               1108
#define IDC_STATIC_ENG                  1109
#define IDC_STATIC_ETC_INFO             1110
#define IDC_STATIC_FILE                 1111
#define IDC_STATIC_FORMAT               1112
#define IDC_STATIC_FORMAT_              1113
#define IDC_STATIC_FORMAT_A             1114
#define IDC_STATIC_FORMAT_A_            1115
#define IDC_STATIC_FORMAT_INFO          1116
#define IDC_STATIC_FORMAT_V             1117
#define IDC_STATIC_FORMAT_V_            1118
#define IDC_STATIC_GNR                  1119
#define IDC_STATIC_GRP                  1120
#define IDC_STATIC_ID3GUIDE             1121
#define IDC_STATIC_ID3TAGV1_NOTE        1122
#define IDC_STATIC_ID3VER               1123
#define IDC_STATIC_INFO                 1124
#define IDC_STATIC_INFOTIP_FORMAT       1125
#define IDC_STATIC_IS_PROTECTED         1126
#define IDC_STATIC_NAM                  1127
#define IDC_STATIC_NOT_MP3              1128
#define IDC_STATIC_ORGART               1129
#define IDC_STATIC_PRD                  1130
#define IDC_STATIC_SEEKABLE             1131
#define IDC_STATIC_SFT                  1132
#define IDC_STATIC_SIZE_INFO            1133
#define IDC_STATIC_SOFT_DEFAULT         1134
#define IDC_STATIC_SRC                  1135
#define IDC_STATIC_TIME                 1136
#define IDC_STATIC_TIME_                1137
#define IDC_STATIC_TOOL                 1138
#define IDC_STATIC_TRACK                1139
#define IDC_STATIC_TRANSLATE            1140
#define IDC_STATIC_TRANSLATOR           1141
#define IDC_STATIC_TRK                  1142
#define IDC_STATIC_URL                  1143
#define IDC_STATIC_URL1                 1144
#define IDC_STATIC_URL2                 1145
#define IDC_STATIC_VER_INFO             1146
#define IDC_STATIC_WINAMP               1147
#define IDC_URL_JUMP                    1148
#define IDI_ICON1                       1149
#define ID_MENU_COPY                    40000
#define ID_MENU_PASTE                   40001

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        220
#define _APS_NEXT_COMMAND_VALUE         40003
#define _APS_NEXT_CONTROL_VALUE         1150
#define _APS_NEXT_SYMED_VALUE           4000
#endif
#endif
